version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
configuration: Release
before_build:
   - nuget restore src
build:
  project: src/Nager.ArticleNumber.sln
  publish_nuget: true
  publish_nuget_symbols: true
  verbosity: normal
deploy:
  provider: NuGet
  api_key:
    secure: F8uBS+uFGqijVbZFwmNkJERqZO6cdMmTxxXM12xPJX6uwu726vyVPuZx8vjlqpAX
  artifact: /.*\.nupkg/